// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/products.proto

package productpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string              `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Seo                  string              `protobuf:"bytes,3,opt,name=seo,proto3" json:"seo,omitempty"`
	Url                  string              `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Vendor               string              `protobuf:"bytes,5,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Tags                 string              `protobuf:"bytes,6,opt,name=tags,proto3" json:"tags,omitempty"`
	Variant              []*Product_Variant  `protobuf:"bytes,7,rep,name=variant,proto3" json:"variant,omitempty"`
	Category             []*Product_Category `protobuf:"bytes,8,rep,name=category,proto3" json:"category,omitempty"`
	CreatedAt            string              `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string              `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_a14f0155623d3d8a, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetSeo() string {
	if m != nil {
		return m.Seo
	}
	return ""
}

func (m *Product) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Product) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *Product) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *Product) GetVariant() []*Product_Variant {
	if m != nil {
		return m.Variant
	}
	return nil
}

func (m *Product) GetCategory() []*Product_Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *Product) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Product) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type Product_Variant struct {
	Id                   string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string                   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ProductOption        []*Product_ProductOption `protobuf:"bytes,3,rep,name=product_option,json=productOption,proto3" json:"product_option,omitempty"`
	Media                []*Product_Media         `protobuf:"bytes,4,rep,name=media,proto3" json:"media,omitempty"`
	Inventory            *Product_Inventory       `protobuf:"bytes,5,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Shipping             *Product_Shipping        `protobuf:"bytes,6,opt,name=shipping,proto3" json:"shipping,omitempty"`
	Price                string                   `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	SalesPrice           string                   `protobuf:"bytes,8,opt,name=sales_price,json=salesPrice,proto3" json:"sales_price,omitempty"`
	Sku                  string                   `protobuf:"bytes,9,opt,name=sku,proto3" json:"sku,omitempty"`
	Taxable              string                   `protobuf:"bytes,10,opt,name=taxable,proto3" json:"taxable,omitempty"`
	Positon              string                   `protobuf:"bytes,11,opt,name=positon,proto3" json:"positon,omitempty"`
	CreatedAt            string                   `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string                   `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Product_Variant) Reset()         { *m = Product_Variant{} }
func (m *Product_Variant) String() string { return proto.CompactTextString(m) }
func (*Product_Variant) ProtoMessage()    {}
func (*Product_Variant) Descriptor() ([]byte, []int) {
	return fileDescriptor_a14f0155623d3d8a, []int{0, 0}
}

func (m *Product_Variant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product_Variant.Unmarshal(m, b)
}
func (m *Product_Variant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product_Variant.Marshal(b, m, deterministic)
}
func (m *Product_Variant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product_Variant.Merge(m, src)
}
func (m *Product_Variant) XXX_Size() int {
	return xxx_messageInfo_Product_Variant.Size(m)
}
func (m *Product_Variant) XXX_DiscardUnknown() {
	xxx_messageInfo_Product_Variant.DiscardUnknown(m)
}

var xxx_messageInfo_Product_Variant proto.InternalMessageInfo

func (m *Product_Variant) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product_Variant) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product_Variant) GetProductOption() []*Product_ProductOption {
	if m != nil {
		return m.ProductOption
	}
	return nil
}

func (m *Product_Variant) GetMedia() []*Product_Media {
	if m != nil {
		return m.Media
	}
	return nil
}

func (m *Product_Variant) GetInventory() *Product_Inventory {
	if m != nil {
		return m.Inventory
	}
	return nil
}

func (m *Product_Variant) GetShipping() *Product_Shipping {
	if m != nil {
		return m.Shipping
	}
	return nil
}

func (m *Product_Variant) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Product_Variant) GetSalesPrice() string {
	if m != nil {
		return m.SalesPrice
	}
	return ""
}

func (m *Product_Variant) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *Product_Variant) GetTaxable() string {
	if m != nil {
		return m.Taxable
	}
	return ""
}

func (m *Product_Variant) GetPositon() string {
	if m != nil {
		return m.Positon
	}
	return ""
}

func (m *Product_Variant) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Product_Variant) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type Product_ProductOption struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product_ProductOption) Reset()         { *m = Product_ProductOption{} }
func (m *Product_ProductOption) String() string { return proto.CompactTextString(m) }
func (*Product_ProductOption) ProtoMessage()    {}
func (*Product_ProductOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_a14f0155623d3d8a, []int{0, 1}
}

func (m *Product_ProductOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product_ProductOption.Unmarshal(m, b)
}
func (m *Product_ProductOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product_ProductOption.Marshal(b, m, deterministic)
}
func (m *Product_ProductOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product_ProductOption.Merge(m, src)
}
func (m *Product_ProductOption) XXX_Size() int {
	return xxx_messageInfo_Product_ProductOption.Size(m)
}
func (m *Product_ProductOption) XXX_DiscardUnknown() {
	xxx_messageInfo_Product_ProductOption.DiscardUnknown(m)
}

var xxx_messageInfo_Product_ProductOption proto.InternalMessageInfo

func (m *Product_ProductOption) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product_ProductOption) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product_ProductOption) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Product_ProductOption) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Product_Media struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Src                  string   `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product_Media) Reset()         { *m = Product_Media{} }
func (m *Product_Media) String() string { return proto.CompactTextString(m) }
func (*Product_Media) ProtoMessage()    {}
func (*Product_Media) Descriptor() ([]byte, []int) {
	return fileDescriptor_a14f0155623d3d8a, []int{0, 2}
}

func (m *Product_Media) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product_Media.Unmarshal(m, b)
}
func (m *Product_Media) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product_Media.Marshal(b, m, deterministic)
}
func (m *Product_Media) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product_Media.Merge(m, src)
}
func (m *Product_Media) XXX_Size() int {
	return xxx_messageInfo_Product_Media.Size(m)
}
func (m *Product_Media) XXX_DiscardUnknown() {
	xxx_messageInfo_Product_Media.DiscardUnknown(m)
}

var xxx_messageInfo_Product_Media proto.InternalMessageInfo

func (m *Product_Media) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product_Media) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

type Product_Inventory struct {
	Quantity             string   `protobuf:"bytes,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ContinueSelling      string   `protobuf:"bytes,2,opt,name=continue_selling,json=continueSelling,proto3" json:"continue_selling,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product_Inventory) Reset()         { *m = Product_Inventory{} }
func (m *Product_Inventory) String() string { return proto.CompactTextString(m) }
func (*Product_Inventory) ProtoMessage()    {}
func (*Product_Inventory) Descriptor() ([]byte, []int) {
	return fileDescriptor_a14f0155623d3d8a, []int{0, 3}
}

func (m *Product_Inventory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product_Inventory.Unmarshal(m, b)
}
func (m *Product_Inventory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product_Inventory.Marshal(b, m, deterministic)
}
func (m *Product_Inventory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product_Inventory.Merge(m, src)
}
func (m *Product_Inventory) XXX_Size() int {
	return xxx_messageInfo_Product_Inventory.Size(m)
}
func (m *Product_Inventory) XXX_DiscardUnknown() {
	xxx_messageInfo_Product_Inventory.DiscardUnknown(m)
}

var xxx_messageInfo_Product_Inventory proto.InternalMessageInfo

func (m *Product_Inventory) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *Product_Inventory) GetContinueSelling() string {
	if m != nil {
		return m.ContinueSelling
	}
	return ""
}

type Product_Shipping struct {
	Weight               string   `protobuf:"bytes,1,opt,name=weight,proto3" json:"weight,omitempty"`
	WeightUnit           string   `protobuf:"bytes,2,opt,name=weight_unit,json=weightUnit,proto3" json:"weight_unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product_Shipping) Reset()         { *m = Product_Shipping{} }
func (m *Product_Shipping) String() string { return proto.CompactTextString(m) }
func (*Product_Shipping) ProtoMessage()    {}
func (*Product_Shipping) Descriptor() ([]byte, []int) {
	return fileDescriptor_a14f0155623d3d8a, []int{0, 4}
}

func (m *Product_Shipping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product_Shipping.Unmarshal(m, b)
}
func (m *Product_Shipping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product_Shipping.Marshal(b, m, deterministic)
}
func (m *Product_Shipping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product_Shipping.Merge(m, src)
}
func (m *Product_Shipping) XXX_Size() int {
	return xxx_messageInfo_Product_Shipping.Size(m)
}
func (m *Product_Shipping) XXX_DiscardUnknown() {
	xxx_messageInfo_Product_Shipping.DiscardUnknown(m)
}

var xxx_messageInfo_Product_Shipping proto.InternalMessageInfo

func (m *Product_Shipping) GetWeight() string {
	if m != nil {
		return m.Weight
	}
	return ""
}

func (m *Product_Shipping) GetWeightUnit() string {
	if m != nil {
		return m.WeightUnit
	}
	return ""
}

type Product_Category struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product_Category) Reset()         { *m = Product_Category{} }
func (m *Product_Category) String() string { return proto.CompactTextString(m) }
func (*Product_Category) ProtoMessage()    {}
func (*Product_Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_a14f0155623d3d8a, []int{0, 5}
}

func (m *Product_Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product_Category.Unmarshal(m, b)
}
func (m *Product_Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product_Category.Marshal(b, m, deterministic)
}
func (m *Product_Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product_Category.Merge(m, src)
}
func (m *Product_Category) XXX_Size() int {
	return xxx_messageInfo_Product_Category.Size(m)
}
func (m *Product_Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Product_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Product_Category proto.InternalMessageInfo

func (m *Product_Category) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product_Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateProductRequest struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductRequest) Reset()         { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()    {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a14f0155623d3d8a, []int{1}
}

func (m *CreateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductRequest.Unmarshal(m, b)
}
func (m *CreateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductRequest.Marshal(b, m, deterministic)
}
func (m *CreateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductRequest.Merge(m, src)
}
func (m *CreateProductRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductRequest.Size(m)
}
func (m *CreateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductRequest proto.InternalMessageInfo

func (m *CreateProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type CreateProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductResponse) Reset()         { *m = CreateProductResponse{} }
func (m *CreateProductResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProductResponse) ProtoMessage()    {}
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a14f0155623d3d8a, []int{2}
}

func (m *CreateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductResponse.Unmarshal(m, b)
}
func (m *CreateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductResponse.Marshal(b, m, deterministic)
}
func (m *CreateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductResponse.Merge(m, src)
}
func (m *CreateProductResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProductResponse.Size(m)
}
func (m *CreateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductResponse proto.InternalMessageInfo

func (m *CreateProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type UpdateProductRequest struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductRequest) Reset()         { *m = UpdateProductRequest{} }
func (m *UpdateProductRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductRequest) ProtoMessage()    {}
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a14f0155623d3d8a, []int{3}
}

func (m *UpdateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductRequest.Unmarshal(m, b)
}
func (m *UpdateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductRequest.Merge(m, src)
}
func (m *UpdateProductRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductRequest.Size(m)
}
func (m *UpdateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductRequest proto.InternalMessageInfo

func (m *UpdateProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type UpdateProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductResponse) Reset()         { *m = UpdateProductResponse{} }
func (m *UpdateProductResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProductResponse) ProtoMessage()    {}
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a14f0155623d3d8a, []int{4}
}

func (m *UpdateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductResponse.Unmarshal(m, b)
}
func (m *UpdateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductResponse.Merge(m, src)
}
func (m *UpdateProductResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProductResponse.Size(m)
}
func (m *UpdateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductResponse proto.InternalMessageInfo

func (m *UpdateProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type ReadProductRequest struct {
	ProductId            string   `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadProductRequest) Reset()         { *m = ReadProductRequest{} }
func (m *ReadProductRequest) String() string { return proto.CompactTextString(m) }
func (*ReadProductRequest) ProtoMessage()    {}
func (*ReadProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a14f0155623d3d8a, []int{5}
}

func (m *ReadProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadProductRequest.Unmarshal(m, b)
}
func (m *ReadProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadProductRequest.Marshal(b, m, deterministic)
}
func (m *ReadProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadProductRequest.Merge(m, src)
}
func (m *ReadProductRequest) XXX_Size() int {
	return xxx_messageInfo_ReadProductRequest.Size(m)
}
func (m *ReadProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadProductRequest proto.InternalMessageInfo

func (m *ReadProductRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type ReadProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadProductResponse) Reset()         { *m = ReadProductResponse{} }
func (m *ReadProductResponse) String() string { return proto.CompactTextString(m) }
func (*ReadProductResponse) ProtoMessage()    {}
func (*ReadProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a14f0155623d3d8a, []int{6}
}

func (m *ReadProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadProductResponse.Unmarshal(m, b)
}
func (m *ReadProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadProductResponse.Marshal(b, m, deterministic)
}
func (m *ReadProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadProductResponse.Merge(m, src)
}
func (m *ReadProductResponse) XXX_Size() int {
	return xxx_messageInfo_ReadProductResponse.Size(m)
}
func (m *ReadProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadProductResponse proto.InternalMessageInfo

func (m *ReadProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type DeleteProductRequest struct {
	ProductId            string   `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductRequest) Reset()         { *m = DeleteProductRequest{} }
func (m *DeleteProductRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProductRequest) ProtoMessage()    {}
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a14f0155623d3d8a, []int{7}
}

func (m *DeleteProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductRequest.Unmarshal(m, b)
}
func (m *DeleteProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductRequest.Marshal(b, m, deterministic)
}
func (m *DeleteProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductRequest.Merge(m, src)
}
func (m *DeleteProductRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProductRequest.Size(m)
}
func (m *DeleteProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductRequest proto.InternalMessageInfo

func (m *DeleteProductRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type DeleteProductResponse struct {
	ProductId            string   `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductResponse) Reset()         { *m = DeleteProductResponse{} }
func (m *DeleteProductResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteProductResponse) ProtoMessage()    {}
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a14f0155623d3d8a, []int{8}
}

func (m *DeleteProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductResponse.Unmarshal(m, b)
}
func (m *DeleteProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductResponse.Marshal(b, m, deterministic)
}
func (m *DeleteProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductResponse.Merge(m, src)
}
func (m *DeleteProductResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteProductResponse.Size(m)
}
func (m *DeleteProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductResponse proto.InternalMessageInfo

func (m *DeleteProductResponse) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type ListProductRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProductRequest) Reset()         { *m = ListProductRequest{} }
func (m *ListProductRequest) String() string { return proto.CompactTextString(m) }
func (*ListProductRequest) ProtoMessage()    {}
func (*ListProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a14f0155623d3d8a, []int{9}
}

func (m *ListProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductRequest.Unmarshal(m, b)
}
func (m *ListProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductRequest.Marshal(b, m, deterministic)
}
func (m *ListProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductRequest.Merge(m, src)
}
func (m *ListProductRequest) XXX_Size() int {
	return xxx_messageInfo_ListProductRequest.Size(m)
}
func (m *ListProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductRequest proto.InternalMessageInfo

type ListProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProductResponse) Reset()         { *m = ListProductResponse{} }
func (m *ListProductResponse) String() string { return proto.CompactTextString(m) }
func (*ListProductResponse) ProtoMessage()    {}
func (*ListProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a14f0155623d3d8a, []int{10}
}

func (m *ListProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductResponse.Unmarshal(m, b)
}
func (m *ListProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductResponse.Marshal(b, m, deterministic)
}
func (m *ListProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductResponse.Merge(m, src)
}
func (m *ListProductResponse) XXX_Size() int {
	return xxx_messageInfo_ListProductResponse.Size(m)
}
func (m *ListProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductResponse proto.InternalMessageInfo

func (m *ListProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "product.Product")
	proto.RegisterType((*Product_Variant)(nil), "product.Product.Variant")
	proto.RegisterType((*Product_ProductOption)(nil), "product.Product.ProductOption")
	proto.RegisterType((*Product_Media)(nil), "product.Product.Media")
	proto.RegisterType((*Product_Inventory)(nil), "product.Product.Inventory")
	proto.RegisterType((*Product_Shipping)(nil), "product.Product.Shipping")
	proto.RegisterType((*Product_Category)(nil), "product.Product.Category")
	proto.RegisterType((*CreateProductRequest)(nil), "product.CreateProductRequest")
	proto.RegisterType((*CreateProductResponse)(nil), "product.CreateProductResponse")
	proto.RegisterType((*UpdateProductRequest)(nil), "product.UpdateProductRequest")
	proto.RegisterType((*UpdateProductResponse)(nil), "product.UpdateProductResponse")
	proto.RegisterType((*ReadProductRequest)(nil), "product.ReadProductRequest")
	proto.RegisterType((*ReadProductResponse)(nil), "product.ReadProductResponse")
	proto.RegisterType((*DeleteProductRequest)(nil), "product.DeleteProductRequest")
	proto.RegisterType((*DeleteProductResponse)(nil), "product.DeleteProductResponse")
	proto.RegisterType((*ListProductRequest)(nil), "product.ListProductRequest")
	proto.RegisterType((*ListProductResponse)(nil), "product.ListProductResponse")
}

func init() {
	proto.RegisterFile("proto/products.proto", fileDescriptor_a14f0155623d3d8a)
}

var fileDescriptor_a14f0155623d3d8a = []byte{
	// 731 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0xd6, 0xd6, 0x76, 0x6d, 0x4f, 0xe8, 0x98, 0x4c, 0x37, 0x99, 0xc0, 0xc6, 0xb4, 0xab, 0x0d,
	0xa1, 0x82, 0x3a, 0x0d, 0x71, 0xbb, 0x15, 0x24, 0x86, 0x60, 0x4c, 0x99, 0xc6, 0x05, 0x12, 0xaa,
	0xbc, 0xc6, 0xea, 0x2c, 0x32, 0x27, 0x4b, 0x9c, 0xc2, 0x5e, 0x84, 0xc7, 0x42, 0x3c, 0x12, 0xb2,
	0x7d, 0x12, 0xd2, 0x24, 0xb0, 0x1f, 0xae, 0x7a, 0x7e, 0xbf, 0x1c, 0x7f, 0xdf, 0xb1, 0x55, 0xe8,
	0x47, 0x71, 0xa8, 0xc2, 0xe7, 0x51, 0x1c, 0xfa, 0xe9, 0x44, 0x25, 0x03, 0xe3, 0x92, 0x36, 0xfa,
	0x5b, 0x3f, 0x3b, 0xd0, 0x3e, 0xb6, 0x36, 0x59, 0x86, 0x45, 0xe1, 0xd3, 0x85, 0xcd, 0x85, 0xed,
	0xae, 0xb7, 0x28, 0x7c, 0xd2, 0x87, 0x96, 0x12, 0x2a, 0xe0, 0x74, 0xd1, 0x84, 0xac, 0x43, 0x56,
	0xa0, 0x91, 0xf0, 0x90, 0x36, 0x4c, 0x4c, 0x9b, 0x3a, 0x92, 0xc6, 0x01, 0x6d, 0xda, 0x48, 0x1a,
	0x07, 0x64, 0x0d, 0x96, 0x66, 0x5c, 0xfa, 0x61, 0x4c, 0x5b, 0x26, 0x88, 0x1e, 0x21, 0xd0, 0x54,
	0x6c, 0x9a, 0xd0, 0x25, 0x13, 0x35, 0x36, 0x19, 0x42, 0x7b, 0xc6, 0x62, 0xc1, 0xa4, 0xa2, 0xed,
	0xcd, 0xc6, 0xb6, 0x33, 0xa4, 0x03, 0x1c, 0x6e, 0x80, 0x83, 0x0d, 0x3e, 0xd9, 0xbc, 0x97, 0x15,
	0x92, 0x3d, 0xe8, 0x4c, 0x98, 0xe2, 0xd3, 0x30, 0xbe, 0xa2, 0x1d, 0xd3, 0xf4, 0xb0, 0xd2, 0x34,
	0xc2, 0x02, 0x2f, 0x2f, 0x25, 0xeb, 0x00, 0x93, 0x98, 0x33, 0xc5, 0xfd, 0x31, 0x53, 0xb4, 0x6b,
	0x86, 0xe8, 0x62, 0x64, 0x5f, 0xe9, 0x74, 0x1a, 0xf9, 0x59, 0x1a, 0x6c, 0x1a, 0x23, 0xfb, 0xca,
	0xfd, 0xd5, 0x80, 0x36, 0x4e, 0x72, 0x43, 0xaa, 0xde, 0xc0, 0x32, 0x4e, 0x35, 0x0e, 0x23, 0x25,
	0x42, 0x49, 0x1b, 0x66, 0xd8, 0x8d, 0xca, 0xb0, 0xf8, 0xfb, 0xd1, 0x54, 0x79, 0xbd, 0xa8, 0xe8,
	0x92, 0x67, 0xd0, 0xba, 0xe0, 0xbe, 0x60, 0xb4, 0x69, 0xba, 0xd7, 0x2a, 0xdd, 0x1f, 0x74, 0xd6,
	0xb3, 0x45, 0xe4, 0x15, 0x74, 0x85, 0x9c, 0x71, 0xa9, 0x34, 0x39, 0x9a, 0x7e, 0x67, 0xe8, 0x56,
	0x3a, 0x0e, 0xb3, 0x0a, 0xef, 0x4f, 0xb1, 0x66, 0x35, 0x39, 0x17, 0x51, 0x24, 0xe4, 0xd4, 0x28,
	0x54, 0xc7, 0xea, 0x09, 0x16, 0x78, 0x79, 0xa9, 0x3e, 0x7b, 0x14, 0x8b, 0x09, 0xa7, 0x6d, 0x7b,
	0x76, 0xe3, 0x90, 0x27, 0xe0, 0x24, 0x2c, 0xe0, 0xc9, 0xd8, 0xe6, 0x3a, 0x26, 0x07, 0x26, 0x74,
	0x6c, 0x0a, 0xf4, 0x1e, 0x7d, 0x4d, 0x51, 0x05, 0x6d, 0x12, 0x0a, 0x6d, 0xc5, 0xbe, 0xb3, 0xb3,
	0x80, 0x23, 0xf9, 0x99, 0xab, 0x33, 0x51, 0x98, 0x08, 0x15, 0x4a, 0xea, 0xd8, 0x0c, 0xba, 0x25,
	0x49, 0xef, 0xfd, 0x5b, 0xd2, 0x5e, 0x59, 0xd2, 0x2f, 0xd0, 0x9b, 0x63, 0xbe, 0xa2, 0x2b, 0x81,
	0xa6, 0x64, 0x17, 0x99, 0xac, 0xc6, 0x36, 0x4b, 0x7c, 0x15, 0x71, 0xbc, 0x01, 0xc6, 0xd6, 0x1c,
	0xcc, 0x58, 0x90, 0x72, 0xbc, 0x04, 0xd6, 0x71, 0x77, 0xa0, 0x65, 0xa4, 0xa9, 0xc0, 0xea, 0xb3,
	0xc7, 0x13, 0x44, 0xd5, 0xa6, 0xeb, 0x41, 0x37, 0xd7, 0x84, 0xb8, 0xd0, 0xb9, 0x4c, 0x99, 0x54,
	0x42, 0x5d, 0x61, 0x53, 0xee, 0x93, 0x1d, 0x58, 0x99, 0x84, 0x52, 0x09, 0x99, 0xf2, 0x71, 0xc2,
	0x83, 0x40, 0x8b, 0x65, 0x71, 0xee, 0x67, 0xf1, 0x13, 0x1b, 0x76, 0x47, 0xd0, 0xc9, 0xe4, 0xd2,
	0x37, 0xf2, 0x1b, 0x17, 0xd3, 0x73, 0x85, 0x80, 0xe8, 0x69, 0x99, 0xac, 0x35, 0x4e, 0xa5, 0x50,
	0x88, 0x04, 0x36, 0x74, 0x2a, 0x85, 0x72, 0x07, 0xd0, 0xc9, 0x6e, 0xd2, 0x4d, 0xd8, 0xd9, 0x3a,
	0x80, 0xfe, 0xc8, 0xd0, 0x8f, 0xc4, 0x7a, 0xfc, 0x32, 0xe5, 0x89, 0x22, 0x4f, 0x21, 0x7b, 0x73,
	0x0c, 0x80, 0x33, 0x5c, 0x29, 0xef, 0x96, 0x97, 0x3f, 0x4a, 0x23, 0x58, 0x2d, 0x61, 0x24, 0x51,
	0x28, 0x13, 0x7e, 0x2b, 0x90, 0x03, 0xe8, 0x9f, 0x1a, 0xa1, 0xff, 0x6f, 0x90, 0x12, 0xc6, 0x1d,
	0x06, 0xd9, 0x05, 0xe2, 0x71, 0xe6, 0x97, 0xc6, 0x58, 0x07, 0xc8, 0xde, 0x86, 0x9c, 0xd3, 0x2e,
	0x46, 0x0e, 0xfd, 0xad, 0x7d, 0x78, 0x30, 0xd7, 0x74, 0x87, 0xef, 0xee, 0x41, 0xff, 0x35, 0x0f,
	0x78, 0x85, 0x80, 0x6b, 0xbe, 0xfc, 0x12, 0x56, 0x4b, 0x6d, 0xf8, 0xed, 0x6b, 0xfa, 0xfa, 0x40,
	0xde, 0x8b, 0x44, 0xcd, 0x7f, 0x4c, 0x9f, 0x63, 0x2e, 0x7a, 0xfb, 0x73, 0x0c, 0x7f, 0x34, 0x60,
	0x19, 0x83, 0x27, 0x3c, 0x9e, 0xe9, 0xb7, 0xe3, 0x08, 0x7a, 0x73, 0x0b, 0x42, 0xd6, 0xf3, 0xf6,
	0xba, 0xe5, 0x73, 0x37, 0xfe, 0x96, 0xc6, 0x71, 0x8e, 0xa0, 0x37, 0xa7, 0x73, 0x01, 0xaf, 0x6e,
	0x87, 0x0a, 0x78, 0xf5, 0xeb, 0x71, 0x04, 0xbd, 0x39, 0x0e, 0x0b, 0x78, 0x75, 0x92, 0x14, 0xf0,
	0xea, 0xa9, 0x7f, 0x0b, 0x4e, 0x61, 0x1b, 0xc8, 0xa3, 0xbc, 0xbc, 0xba, 0x58, 0xee, 0xe3, 0xfa,
	0x24, 0x22, 0xbd, 0x03, 0xa7, 0xa0, 0x47, 0x01, 0xa9, 0xaa, 0x5d, 0x01, 0xa9, 0x46, 0xc2, 0x17,
	0x0b, 0x07, 0xce, 0xe7, 0x4c, 0xfe, 0xe8, 0xec, 0x6c, 0xc9, 0xfc, 0xb1, 0xd8, 0xfd, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0x7f, 0x27, 0x32, 0x7a, 0x70, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error)
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error)
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error)
	ReadProduct(ctx context.Context, in *ReadProductRequest, opts ...grpc.CallOption) (*ReadProductResponse, error)
	ListProduct(ctx context.Context, in *ListProductRequest, opts ...grpc.CallOption) (ProductService_ListProductClient, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error) {
	out := new(CreateProductResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/CreateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error) {
	out := new(UpdateProductResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/UpdateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error) {
	out := new(DeleteProductResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/DeleteProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ReadProduct(ctx context.Context, in *ReadProductRequest, opts ...grpc.CallOption) (*ReadProductResponse, error) {
	out := new(ReadProductResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/ReadProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListProduct(ctx context.Context, in *ListProductRequest, opts ...grpc.CallOption) (ProductService_ListProductClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProductService_serviceDesc.Streams[0], "/product.ProductService/ListProduct", opts...)
	if err != nil {
		return nil, err
	}
	x := &productServiceListProductClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProductService_ListProductClient interface {
	Recv() (*ListProductResponse, error)
	grpc.ClientStream
}

type productServiceListProductClient struct {
	grpc.ClientStream
}

func (x *productServiceListProductClient) Recv() (*ListProductResponse, error) {
	m := new(ListProductResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error)
	UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error)
	DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductResponse, error)
	ReadProduct(context.Context, *ReadProductRequest) (*ReadProductResponse, error)
	ListProduct(*ListProductRequest, ProductService_ListProductServer) error
}

// UnimplementedProductServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (*UnimplementedProductServiceServer) CreateProduct(ctx context.Context, req *CreateProductRequest) (*CreateProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (*UnimplementedProductServiceServer) UpdateProduct(ctx context.Context, req *UpdateProductRequest) (*UpdateProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (*UnimplementedProductServiceServer) DeleteProduct(ctx context.Context, req *DeleteProductRequest) (*DeleteProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (*UnimplementedProductServiceServer) ReadProduct(ctx context.Context, req *ReadProductRequest) (*ReadProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadProduct not implemented")
}
func (*UnimplementedProductServiceServer) ListProduct(req *ListProductRequest, srv ProductService_ListProductServer) error {
	return status.Errorf(codes.Unimplemented, "method ListProduct not implemented")
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/CreateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/UpdateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/DeleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteProduct(ctx, req.(*DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ReadProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ReadProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/ReadProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ReadProduct(ctx, req.(*ReadProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListProduct_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListProductRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProductServiceServer).ListProduct(m, &productServiceListProductServer{stream})
}

type ProductService_ListProductServer interface {
	Send(*ListProductResponse) error
	grpc.ServerStream
}

type productServiceListProductServer struct {
	grpc.ServerStream
}

func (x *productServiceListProductServer) Send(m *ListProductResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProduct",
			Handler:    _ProductService_CreateProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _ProductService_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _ProductService_DeleteProduct_Handler,
		},
		{
			MethodName: "ReadProduct",
			Handler:    _ProductService_ReadProduct_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListProduct",
			Handler:       _ProductService_ListProduct_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/products.proto",
}
